### ISSUE TITLE
About the Popup's style

### ISSUE THREAD

**Issue by weita0** [minutemailer/react-popup#12]
I'm a newbie of React. And when I try to use react-popup in my project, I find that the style is totally not applied. And I wonder where is the css staff.

**Comment by tbleckert** [comment]
Hi!

We are not using inline styles (yet) so the styles comes from the demo CSS (which probably should be documented in the README). We will however transition to using inline styles as soon as possible. For now, take a look at this https://github.com/minutemailer/react-popup/blob/gh-pages/popup.example.css
