### ISSUE TITLE
awesome and works as described, but default styles please?

### ISSUE THREAD

**Issue by noahehall** [minutemailer/react-popup#15]
would be great if you can add the styles used here http://minutemailer.github.io/react-popup/

**Comment by tbleckert** [comment]
Thank you, I'm working on it and hopefully it will be available soon. Until then you can access the styles (and example code) from the gh-pages branch https://github.com/minutemailer/react-popup/tree/gh-pages

**Comment by noahehall** [comment]
ooh thanks man!
