### ISSUE TITLE
Receive 'Warning: PopupInput is changing an uncontrolled input of the type text to be controlled.' when implementing react-popup

### ISSUE THREAD

**Issue by ryndshn** [minutemailer/react-popup#19]
I receive the following warning when implementing react-popup. Is this a problem on my part? I am following example code precisely. 

![image](https://cloud.githubusercontent.com/assets/10523324/23367857/d79d2484-fcd9-11e6-85ac-dc34e8cdb612.png)

**Comment by tbleckert** [comment]
Which version of the popup are you using and what is your version of React? Do you get the same error on the demo page? Can you show me the code that causes this error?

**Comment by tbleckert** [comment]
Closing this since we no longer have built in support for prompts (that include the input)
