### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by SkyJedi** [minutemailer/react-popup#25]
I'm getting these errors when i load in my project

warning.js:36 Warning: PopupHeader: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by tbleckert** [comment]
Thanks, that's due to an update in React. You should still be able to use the package though. I will see if I can manage to work on a patch during the day.  I'll let you know when it's up.

**Comment by SkyJedi** [comment]
I thought so.  I did get the popups working with your stylesheets, now to get a form working in the popup.  Thanks for this awesome module!

**Comment by tbleckert** [comment]
Nice! I'm glad you like it!

**Comment by z-vr** [comment]
@SkyJedi if you use `react-form` you will have to use `ref` property 

```
let form;
const submitFunction = () => {
    if (form && typeof form.submitForm === 'function') {
        form.submitForm();
    }
};
const formComponent = (
    <Form
    ref={(el) => { if (el) { form = el; } }}
    onSuccess={() => {
        Popup.close();
    }}
    />
);

Popup.create({
    title: `Form`,
    content: formComponent,
    className: 'alert',
    buttons: {
        right: [
            {
                text: 'Cancel',
                className: 'danger',
                action: Popup.close,
            },
            {
                text: 'Add',
                className: 'success',
                action: submitFunction,
            },
        ],
    },
});
```

**Comment by tbleckert** [comment]
The warnings should now be gone in the latest release (0.8.0)

**Comment by SkyJedi** [comment]
Thanks for the fix!

I'm still getting 0.7.1 on npm install react-popup

**Comment by tbleckert** [comment]
On a new install? Strange. Or maybe you have it in your package.json with 0.7.1?

**Comment by SkyJedi** [comment]
Thanks! that was the issue.  Totally me, youre awesome

**Comment by tbleckert** [comment]
Hehe no problem, glad it works now!
