### ISSUE TITLE
Demo render issue

### ISSUE THREAD

**Issue by soundslikeodd** [minutemailer/react-popup#26]
Looks like the Demo page has some rendering issues.  In the prompt plugin example the `render()` method and the `content` member of the `create()` call are blank.  
![demo-render-issue](https://cloud.githubusercontent.com/assets/16770697/26167776/a10cf268-3aec-11e7-8a7d-017d57234c1f.jpg)
Looks like some kind of post processing with the gh-page because the raw html looks fine, https://github.com/minutemailer/react-popup/blob/gh-pages/index.html.

**Comment by tbleckert** [comment]
Weird...but thanks! Might be a problem with prism.js also. I'll look it up!
