### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tbleckert** [minutemailer/react-popup#3]
Target "cancel" button on `ESC` and "ok" button on `ENTER`.

**Comment by minisemi** [comment]
Does this work yet, or is it still under development? :)

**Comment by tbleckert** [comment]
I haven't unfortunately been able to free the time to implement this. But it's a rather quick thing to implement. I could have it done in a day or two if you are interested

**Comment by minisemi** [comment]
Totally understandable! Yeah I believe it would be an awesome feature that many would benefit from, especially the `esc` button to hide the popup window. So if you feel that you have the time it would really be appreciated! :D

**Comment by tbleckert** [comment]
Agree! I'll keep you posted on the progress!

**Comment by tbleckert** [comment]
This feature is now available in v0.9.0!
