### ISSUE TITLE
New line not working on content property

### ISSUE THREAD

**Issue by minisemi** [minutemailer/react-popup#30]
Trying to create a new line for the content property of a Popup, but it's not working. Am I perhaps doing it wrong or is it simply not implemented?

Trying to write: `content: "Are you sure you want to cancel the following booking? <br> Soccer field"`

**Comment by tbleckert** [comment]
The content property takes either a plane string or a component, you can't use HTML in a string. For example:

```jsx
{
    content: <div>Are you sure you want to cancel the following booking? <br /> Soccer field</div>
}
```

**Comment by minisemi** [comment]
Awesome, thanks! Tried with a `var text = "first line <br/> second line"` which worked at another place, hence I thought it would here too. But putting it in a div makes more sense, it was just me who presumed it only took strings.

**Comment by tbleckert** [comment]
Yeah, I just decided to not support it since it can be unsafe. Also it adds a bit more logic to the code.
