### ISSUE TITLE
0.8.0 specifying popup position broke

### ISSUE THREAD

**Issue by BradStell** [minutemailer/react-popup#33]
I just upgraded from 0.7.1 this morning and all my popups that were being rendered in a specific location - via the position attribute - have all started showing up in the upper center of the screen. Was there a breaking change for how to specify the position of the popup?

I am currently using it like so:
`Popup.create({
        ...
        position: {
                x: // some number
                y: // some number
         },
         ...
`

**Comment by tbleckert** [comment]
Hi! Sorry for the (super)late reply. Nothing has changed in the API, that's how you do it. I can confirm that this works in 0.9.0. I will try to get a chance to test 0.8.0 as well. If possible, try to update to 0.9.x as it also contains React 16 support, bugfixes and keyboard shortcuts feature.

**Comment by tbleckert** [comment]
I'm closing this. Please let me know if this is still an issue.
