### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by hjaltisan** [minutemailer/react-popup#37]
Support for React 16 is missing

**Comment by JustFly1984** [comment]
Yes, please make it supporting React 16

**Comment by tbleckert** [comment]
Coming soon, hopefully today. The code is ready and exist in master together with some new features. Just need to test it a bit more before publishing the new release.

**Comment by jherencia** [comment]
Hi! any news about this?

**Comment by tbleckert** [comment]
@jherencia sorry for the delay, lots to finish before the holidays :/ But I'm doing some last tweaks and will definitely release it today. The React 16 adjustments is already in place, it's just that we already had some new features in the pipe that we wanted to release at the same time.

**Comment by tbleckert** [comment]
React 16 support is now available in v0.9.0 together with keyboard shortcuts

**Comment by jherencia** [comment]
Thank you very much @tbleckert !
