### ISSUE TITLE
Can't resolve 'keymaster' in 0.9.0

### ISSUE THREAD

**Issue by hongbo-miao** [minutemailer/react-popup#41]
After updating to 0.9.0, got this issue when `npm start`

> Failed to compile
> ./node_modules/react-popup/dist/Popup.react.js
> Module not found: Can't resolve 'keymaster' in '/my-project/node_modules/react-popup/dist'

**Comment by tbleckert** [comment]
When updating you should've gotten a notice about keymaster being required. As React (and React DOM), Keymaster is listed as a peer dependency. Simply `npm install keymaster`. Maybe this should be in the documentation or maybe even a direct dependency.

In npm 3 they removed automatic installs of peer dependencies and I know that have caused some confusion for lots of developers.

**Comment by hongbo-miao** [comment]
Oh, actually have more issues. Still same codes

```html
<Popup
  closeBtn={false}
  closeOnOutsideClick={true}
  escToClose={true} />
```

```js
const popup = Popup.register({
  content: <MyComponent />,
  noOverlay: false
});
```

After installing

```
    "keymaster": "1.6.2",
    "react-popup": "0.9.0",
```
met this

![image](https://user-images.githubusercontent.com/3375461/34278628-eb005fac-e660-11e7-9a7e-7ce457e6e4c5.png)

**Comment by tbleckert** [comment]
Yeah, I saw that too late, but was patched in 0.9.1 minutes after 0.9.0. A tip is to always install for example ~0.9.0 or 0.9.x, regardless of which package you're using, that'll ensure you'll always have patches.

**Comment by hongbo-miao** [comment]
Thanks, I will try again when npm shows 0.9.1

**Comment by hongbo-miao** [comment]
Works perfect now! Even another ESC not respond issue also fixed! Thank you so much!

**Comment by tbleckert** [comment]
Glad it works and thanks for the bug reports!
