### ISSUE TITLE
Error when adding popup to project

### ISSUE THREAD

**Issue by AllanCodes** [minutemailer/react-popup#49]
Hello, I get this error when I add to my index.js file.

`Target container is not a DOM element.`

```
ReactDOM.render(<Main />, document.getElementById('root'));
ReactDOM.render(<Popup />, document.getElementById('popupContainer'));
```
Any ideas what the issue can be?  Should I create the element popupContainer somewhere?

**Comment by tbleckert** [comment]
Do you have an element with the id 'popupContainer' in your HTML?

**Comment by AllanCodes** [comment]
I've now added popupContainer and get no error, however placing this above my class definition

`Popup.alert('Hello');`
doesn't do anything.  I need mention that my ReactDOM.render is in my index.js file and the Popup.alert() is in another class file

**Comment by tbleckert** [comment]
You need to style the component, to start with you can use the [demo css](https://github.com/minutemailer/react-popup/blob/gh-pages/popup.example.css)
