### ISSUE TITLE
React and ReactDOM should be as peerDependency

### ISSUE THREAD

**Issue by Moussawi7** [minutemailer/react-popup#5]
Dear,
First, thank for this awesome work, but may you have to update your package.json.
it show:

```
"dependencies": {
    "react": "^0.14.0",
    "react-dom": "^0.14.0"
  },
```

So it will import react and react-dom even if they are already included, so may you have to put them in the peerDependency so they will be included only if they are missing.
http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
Thanks.

**Comment by tbleckert** [comment]
Thank you!

And thanks for the dependency notice, will make a new release today.
