### ISSUE TITLE
Uncaught TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by kesha-antonov** [minutemailer/react-popup#56]
Got error when import. Using preact

![screen shot 2018-07-26 at 13 04 30](https://user-images.githubusercontent.com/11584712/43256139-82067b02-90d4-11e8-84db-5fca77b7187d.png)

**Comment by tbleckert** [comment]
Strange. Does this happen right away or after a certain action? How is your setup looking?

I haven't tested this against preact yet but it shouldn't make a difference.

**Comment by tbleckert** [comment]
I think the best way to approach this is to offer separate bundles for preact and maybe a few other react alternatives.

**Comment by kesha-antonov** [comment]
I should init my js code after dom loaded or something like that.

**Comment by kesha-antonov** [comment]
Thanks! @tbleckert
