### ISSUE TITLE
Closing popup with back button

### ISSUE THREAD

**Issue by sevban** [minutemailer/react-popup#57]
Is it possible to close the popup with android back button or browser back button?

**Comment by tbleckert** [comment]
It's possible. We won't add it as a feature but I think it should be handled outside anyway.

You have to available events for this, `open` (`addOpenListener`) and `close` (`addCloseListener`). My suggestion is that you add a hash to the URL like "#popupOpen" then add a `hashchanged` listener to detect if "#popupOpen" gets removed, and if so, call `Popup.close()`.
