### ISSUE TITLE
React.createElement Warning

### ISSUE THREAD

**Issue by ghost** [minutemailer/react-popup#9]
If I use your package i get following error when I place the `<Popup />` :

> bundle.js:1374 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

&nbsp;

The Package seems really good, especially the queuing and the ability to reuse popups. There are two things that maybe should be fixed.
- In the install section you are using React.render() instead of ReactDOM.render().  In v0.14 Facebook have split it up into react and react-dom.
- You are also not mentioning if it should be placed in the Root or in the Component

**Comment by tbleckert** [comment]
Hi!

Thanks, that's a new warning that came when I switched to React 15, I'll fix it in the next release.
- We are using react-dom but it seems that I have forgotten to edit the Readme, thanks for making me aware of that. In the demo/documentation page it's correct.
- I will add that, sorry. To answer the question, the component should be mounted in a direct child of the html body.

And I'm happy to hear that you like it. Let me know if you have any ideas for improvement and feel free to send in PR's.
